RETURN_SOURCE_DOCUMENTS: False
VECTOR_COUNT: 1
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: 'documents/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'models/llama-2-7b-chat.ggmlv3.q4_K_M.bin'
MAX_NEW_TOKENS: 100
TEMPERATURE: 0.3